### ISSUE TITLE
-sd option not working in Bamboo

### ISSUE THREAD

**Issue by Vahila** [mathworks/matlab-bamboo-plugin#37]
When using -sd option, the build is not starting in the starting directory path.
![image](https://github.com/mathworks/matlab-bamboo-plugin/assets/70003902/effc6ae6-d69a-4c43-b2ed-b05442403fd6)
![image](https://github.com/mathworks/matlab-bamboo-plugin/assets/70003902/72757997-d683-4185-bd9c-f9b3f5dfc9f4)

When -sd C:\Users\kapilg is specified, the build is not starting from the mentioned directory

**Comment by sameagen-MW** [comment]
Thanks for catching this! Looks like I totally forgot to update the Bamboo plugin when I was updating the other integrations. I think I just need to switch it to using the environment variable like the other platforms. I'll try to have that PR up today.

**Comment by sameagen-MW** [comment]
Okay, the new fix should be in. I'll apply the same change to the TeamCity plugin, which I think has the same issue.
